name: cat_trivia
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  retrofit: ^3.0.1+1
  equatable: ^2.0.3
  json_serializable: ^6.3.1
  logger: ^1.1.0
  dio: ^4.0.6
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  hive_generator: ^1.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.2
  injectable_generator: ^1.5.4
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
